### ISSUE TITLE
One escaping function to rule them all

### ISSUE THREAD

**Issue by flohdot** [PeerioTechnologies/peerio-client-api#64]
In order to remove the threat of unescaped JS injection,t is recommended to route all user-generated/external strings (e.g. usernames, messages, timestamps, translations) through a single place, to be escaped and/or validated by very strict domain-specific rules. JS and HTML contexts will have different escaping rules. A library that might greatly help this process is http://fitzgen.github.io/reform/ For things like usernames, we can possibly copy some of the server-side validation rules.

**Comment by anri-asaturov** [comment]
We use React for that already
